/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AwsOptions : Options for creating an AWS environment



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AwsOptions {
    /// AWS IAM role ARN for Snyk
    #[serde(rename = "role_arn")]
    pub role_arn: String,
}

impl AwsOptions {
    /// Options for creating an AWS environment
    pub fn new(role_arn: String) -> AwsOptions {
        AwsOptions {
            role_arn,
        }
    }
}


