/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AzureOptions : Options for creating an Azure environment



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AzureOptions {
    /// ID of the Azure app registration with permissions to scan
    #[serde(rename = "application_id", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    /// ID of the Azure subscription to be scanned
    #[serde(rename = "subscription_id", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    /// Azure Tenant (directory) ID
    #[serde(rename = "tenant_id", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl AzureOptions {
    /// Options for creating an Azure environment
    pub fn new() -> AzureOptions {
        AzureOptions {
            application_id: None,
            subscription_id: None,
            tenant_id: None,
        }
    }
}


