/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContainerBuildArgs {
    #[serde(rename = "platform")]
    pub platform: String,
}

impl ContainerBuildArgs {
    pub fn new(platform: String) -> ContainerBuildArgs {
        ContainerBuildArgs {
            platform,
        }
    }
}


