/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateScanRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CreateScanRequestData>,
}

impl CreateScanRequest {
    pub fn new(data: crate::models::CreateScanRequestData) -> CreateScanRequest {
        CreateScanRequest {
            data: Box::new(data),
        }
    }
}


