/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePermissionsAttributesOptions {
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<Box<crate::models::CreatePermissionsAttributesOptionsSchema>>,
}

impl CreatePermissionsAttributesOptions {
    pub fn new() -> CreatePermissionsAttributesOptions {
        CreatePermissionsAttributesOptions {
            schema: None,
        }
    }
}


