/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePermissionsAttributes {
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::CreatePermissionsAttributesOptions>>,
    #[serde(rename = "platform")]
    pub platform: Platform,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl CreatePermissionsAttributes {
    pub fn new(platform: Platform, r#type: RHashType) -> CreatePermissionsAttributes {
        CreatePermissionsAttributes {
            options: None,
            platform,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "aws")]
    Aws,
    #[serde(rename = "azure")]
    Azure,
    #[serde(rename = "google")]
    Google,
}

impl Default for Platform {
    fn default() -> Platform {
        Self::Aws
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "cf")]
    Cf,
    #[serde(rename = "tf")]
    Tf,
    #[serde(rename = "bash")]
    Bash,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Cf
    }
}

