/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEnvironmentRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CreateEnvironmentRequestData>,
}

impl CreateEnvironmentRequest {
    pub fn new(data: crate::models::CreateEnvironmentRequestData) -> CreateEnvironmentRequest {
        CreateEnvironmentRequest {
            data: Box::new(data),
        }
    }
}


