/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateScanRequestData {
    /// Scan create attributes
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::ScanCreateRelationships>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CreateScanRequestData {
    pub fn new(r#type: String) -> CreateScanRequestData {
        CreateScanRequestData {
            attributes: None,
            relationships: None,
            r#type,
        }
    }
}


