/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrgInvitationRequest {
    /// The invitee email address.
    #[serde(rename = "email")]
    pub email: String,
    /// The role public ID that will be granted to to invitee on acceptance.
    #[serde(rename = "role")]
    pub role: uuid::Uuid,
}

impl CreateOrgInvitationRequest {
    pub fn new(email: String, role: uuid::Uuid) -> CreateOrgInvitationRequest {
        CreateOrgInvitationRequest {
            email,
            role,
        }
    }
}


