/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreatePermissionsAttributesOptionsSchemaAnyOf : Options for generating an Azure environment permissions script



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePermissionsAttributesOptionsSchemaAnyOf {
    /// ID of the Azure subscription to be scanned
    #[serde(rename = "subscription_id", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    /// Azure Tenant (directory) ID
    #[serde(rename = "tenant_id", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl CreatePermissionsAttributesOptionsSchemaAnyOf {
    /// Options for generating an Azure environment permissions script
    pub fn new() -> CreatePermissionsAttributesOptionsSchemaAnyOf {
        CreatePermissionsAttributesOptionsSchemaAnyOf {
            subscription_id: None,
            tenant_id: None,
        }
    }
}


