/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateContainerImageRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::Image>,
}

impl CreateContainerImageRequest {
    pub fn new(data: crate::models::Image) -> CreateContainerImageRequest {
        CreateContainerImageRequest {
            data: Box::new(data),
        }
    }
}


