/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeprecatedRelationshipData {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Type of the related resource
    #[serde(rename = "type")]
    pub r#type: String,
}

impl DeprecatedRelationshipData {
    pub fn new(id: uuid::Uuid, r#type: String) -> DeprecatedRelationshipData {
        DeprecatedRelationshipData {
            id,
            r#type,
        }
    }
}


