/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EnvironmentUpdateAttributes : Environment update attributes. Only the AWS role ARN can be updated; new ARN must have the same account ID as the old ARN.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EnvironmentUpdateAttributes {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "options")]
    pub options: Box<crate::models::EnvironmentCreateAttributesOptions>,
}

impl EnvironmentUpdateAttributes {
    /// Environment update attributes. Only the AWS role ARN can be updated; new ARN must have the same account ID as the old ARN.
    pub fn new(options: crate::models::EnvironmentCreateAttributesOptions) -> EnvironmentUpdateAttributes {
        EnvironmentUpdateAttributes {
            name: None,
            options: Box::new(options),
        }
    }
}


