/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EnvironmentCreateAttributes {
    /// Environment kind: aws
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Environment name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "options")]
    pub options: Box<crate::models::EnvironmentCreateAttributesOptions>,
}

impl EnvironmentCreateAttributes {
    pub fn new(options: crate::models::EnvironmentCreateAttributesOptions) -> EnvironmentCreateAttributes {
        EnvironmentCreateAttributes {
            kind: None,
            name: None,
            options: Box::new(options),
        }
    }
}


