/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorDocument {
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::Error>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
}

impl ErrorDocument {
    pub fn new(errors: Vec<crate::models::Error>, jsonapi: crate::models::JsonApi) -> ErrorDocument {
        ErrorDocument {
            errors,
            jsonapi: Box::new(jsonapi),
        }
    }
}


