/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetGroup200Response {
    #[serde(rename = "data")]
    pub data: Box<crate::models::Group>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::Links>,
}

impl GetGroup200Response {
    pub fn new(data: crate::models::Group, jsonapi: crate::models::JsonApi, links: crate::models::Links) -> GetGroup200Response {
        GetGroup200Response {
            data: Box::new(data),
            jsonapi: Box::new(jsonapi),
            links: Box::new(links),
        }
    }
}


