/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPermissionsRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CreatePermissionsAttributes>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl GetPermissionsRequestData {
    pub fn new(attributes: crate::models::CreatePermissionsAttributes, r#type: String) -> GetPermissionsRequestData {
        GetPermissionsRequestData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


