/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetPermissions201ResponseData : permissions resource object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPermissions201ResponseData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::PermissionsAttributes>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl GetPermissions201ResponseData {
    /// permissions resource object
    pub fn new(attributes: crate::models::PermissionsAttributes, id: uuid::Uuid, r#type: String) -> GetPermissions201ResponseData {
        GetPermissions201ResponseData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}


