/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUser200Response {
    #[serde(rename = "data")]
    pub data: Box<crate::models::User>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
}

impl GetUser200Response {
    pub fn new(data: crate::models::User, jsonapi: crate::models::JsonApi) -> GetUser200Response {
        GetUser200Response {
            data: Box::new(data),
            jsonapi: Box::new(jsonapi),
        }
    }
}


