/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GoogleOptions : Options for creating a Google environment



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GoogleOptions {
    /// Google project ID
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Google service account email
    #[serde(rename = "service_account_email")]
    pub service_account_email: String,
}

impl GoogleOptions {
    /// Options for creating a Google environment
    pub fn new(service_account_email: String) -> GoogleOptions {
        GoogleOptions {
            project_id: None,
            service_account_email,
        }
    }
}


