/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupAttributes {
    /// The name of the group.
    #[serde(rename = "name")]
    pub name: String,
}

impl GroupAttributes {
    pub fn new(name: String) -> GroupAttributes {
        GroupAttributes {
            name,
        }
    }
}


