/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Image {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::ImageAttributes>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl Image {
    pub fn new(attributes: crate::models::ImageAttributes, id: String, r#type: RHashType) -> Image {
        Image {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "container_image")]
    ContainerImage,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ContainerImage
    }
}

