/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkProperty {
    /// A string containing the link’s URL.
    #[serde(rename = "href")]
    pub href: String,
    /// Free-form object that may contain non-standard information.
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl LinkProperty {
    pub fn new(href: String) -> LinkProperty {
        LinkProperty {
            href,
            meta: None,
        }
    }
}


