/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListGroups200Response {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::Group>,
    #[serde(rename = "jsonapi")]
    pub jsonapi: Box<crate::models::JsonApi>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::Links>,
}

impl ListGroups200Response {
    pub fn new(data: Vec<crate::models::Group>, jsonapi: crate::models::JsonApi, links: crate::models::Links) -> ListGroups200Response {
        ListGroups200Response {
            data,
            jsonapi: Box::new(jsonapi),
            links: Box::new(links),
        }
    }
}


