/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Org {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::OrgAttributes>>,
    /// The Snyk ID corresponding to this org
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Content type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Org {
    pub fn new(id: uuid::Uuid, r#type: String) -> Org {
        Org {
            attributes: None,
            id,
            r#type,
        }
    }
}


