/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrgInvitationRelationships {
    #[serde(rename = "org", skip_serializing_if = "Option::is_none")]
    pub org: Option<Box<crate::models::Relationship>>,
}

impl OrgInvitationRelationships {
    pub fn new() -> OrgInvitationRelationships {
        OrgInvitationRelationships {
            org: None,
        }
    }
}


