/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrgAttributes {
    /// The ID of a Group.
    #[serde(rename = "group_id", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<uuid::Uuid>,
    /// Whether this organization belongs to an individual, rather than a Group.
    #[serde(rename = "is_personal")]
    pub is_personal: bool,
    /// Friendly name of the organization.
    #[serde(rename = "name")]
    pub name: String,
    /// Unique URL sanitized name of the organization for accessing it in Snyk.
    #[serde(rename = "slug")]
    pub slug: String,
}

impl OrgAttributes {
    pub fn new(is_personal: bool, name: String, slug: String) -> OrgAttributes {
        OrgAttributes {
            group_id: None,
            is_personal,
            name,
            slug,
        }
    }
}


