/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchProjectRequestDataAttributes {
    /// Test frequency of a project. Also controls when automated PRs may be created.
    #[serde(rename = "test_frequency", skip_serializing_if = "Option::is_none")]
    pub test_frequency: Option<TestFrequency>,
}

impl PatchProjectRequestDataAttributes {
    pub fn new() -> PatchProjectRequestDataAttributes {
        PatchProjectRequestDataAttributes {
            test_frequency: None,
        }
    }
}

/// Test frequency of a project. Also controls when automated PRs may be created.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TestFrequency {
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "never")]
    Never,
}

impl Default for TestFrequency {
    fn default() -> TestFrequency {
        Self::Daily
    }
}

