/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PermissionsAttributes {
    #[serde(rename = "data")]
    pub data: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl PermissionsAttributes {
    pub fn new(data: String, r#type: RHashType) -> PermissionsAttributes {
        PermissionsAttributes {
            data,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "cf")]
    Cf,
    #[serde(rename = "tf")]
    Tf,
    #[serde(rename = "bash")]
    Bash,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Cf
    }
}

