/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectDeprecatedRelationships {
    #[serde(rename = "importingUser", skip_serializing_if = "Option::is_none")]
    pub importing_user: Option<Box<crate::models::DeprecatedRelationship>>,
    #[serde(rename = "org", skip_serializing_if = "Option::is_none")]
    pub org: Option<Box<crate::models::DeprecatedRelationship>>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::DeprecatedRelationship>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<crate::models::DeprecatedRelationship>>,
}

impl ProjectDeprecatedRelationships {
    pub fn new() -> ProjectDeprecatedRelationships {
        ProjectDeprecatedRelationships {
            importing_user: None,
            org: None,
            owner: None,
            target: None,
        }
    }
}


