/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectDeprecatedAttributes {
    #[serde(rename = "businessCriticality", skip_serializing_if = "Option::is_none")]
    pub business_criticality: Option<Vec<String>>,
    /// The date that the project was created on
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<Vec<String>>,
    #[serde(rename = "lifecycle", skip_serializing_if = "Option::is_none")]
    pub lifecycle: Option<Vec<String>>,
    #[serde(rename = "name")]
    pub name: String,
    /// The origin the project was added from
    #[serde(rename = "origin")]
    pub origin: String,
    /// Describes if a project is currently monitored or it is de-activated
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::Tag>>,
    /// The identifier for which revision of the resource is scanned by Snyk. For example this may be a branch for SCM project, or a tag for a container image
    #[serde(rename = "targetReference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_reference: Option<Option<String>>,
    /// The package manager of the project
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ProjectDeprecatedAttributes {
    pub fn new(created: String, name: String, origin: String, status: String, r#type: String) -> ProjectDeprecatedAttributes {
        ProjectDeprecatedAttributes {
            business_criticality: None,
            created,
            environment: None,
            lifecycle: None,
            name,
            origin,
            status,
            tags: None,
            target_reference: None,
            r#type,
        }
    }
}


