/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectAttributesBuildArgs {
    #[serde(rename = "root_workspace", skip_serializing_if = "Option::is_none")]
    pub root_workspace: Option<String>,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "target_framework")]
    pub target_framework: String,
}

impl ProjectAttributesBuildArgs {
    pub fn new(platform: String, target_framework: String) -> ProjectAttributesBuildArgs {
        ProjectAttributesBuildArgs {
            root_workspace: None,
            platform,
            target_framework,
        }
    }
}


