/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectDeprecated {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::ProjectDeprecatedAttributes>,
    /// The ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::ProjectDeprecatedRelationships>>,
    /// Content type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ProjectDeprecated {
    pub fn new(attributes: crate::models::ProjectDeprecatedAttributes, id: uuid::Uuid, r#type: String) -> ProjectDeprecated {
        ProjectDeprecated {
            attributes: Box::new(attributes),
            id,
            relationships: None,
            r#type,
        }
    }
}


