/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelatedLink {
    #[serde(rename = "related", skip_serializing_if = "Option::is_none")]
    pub related: Option<Box<crate::models::LinkProperty>>,
}

impl RelatedLink {
    pub fn new() -> RelatedLink {
        RelatedLink {
            related: None,
        }
    }
}


