/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemedyDetails {
    /// A minimum version to upgrade to in order to remedy the issue.
    #[serde(rename = "upgrade_package", skip_serializing_if = "Option::is_none")]
    pub upgrade_package: Option<String>,
}

impl RemedyDetails {
    pub fn new() -> RemedyDetails {
        RemedyDetails {
            upgrade_package: None,
        }
    }
}


