/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScanCreateRelationships : Scan create relationships



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScanCreateRelationships {
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<Box<crate::models::ScanCreateRelationshipsEnvironment>>,
}

impl ScanCreateRelationships {
    /// Scan create relationships
    pub fn new() -> ScanCreateRelationships {
        ScanCreateRelationships {
            environment: None,
        }
    }
}


