/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SsoConnectionAttributes {
    /// The display name of the sso connection.
    #[serde(rename = "name")]
    pub name: String,
}

impl SsoConnectionAttributes {
    pub fn new(name: String) -> SsoConnectionAttributes {
        SsoConnectionAttributes {
            name,
        }
    }
}


