/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Target {
    #[serde(rename = "data")]
    pub data: Box<crate::models::TargetData>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::RelatedLink>,
}

impl Target {
    pub fn new(data: crate::models::TargetData, links: crate::models::RelatedLink) -> Target {
        Target {
            data: Box::new(data),
            links: Box::new(links),
        }
    }
}


