/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::TargetDataAttributes>,
    /// The Resource ID.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The Resource type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl TargetData {
    pub fn new(attributes: crate::models::TargetDataAttributes, id: uuid::Uuid, r#type: String) -> TargetData {
        TargetData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}


