/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateUserRequestDataAttributes {
    #[serde(rename = "membership", deserialize_with = "Option::deserialize")]
    pub membership: Option<Box<crate::models::UpdateUserRequestDataAttributesMembership>>,
}

impl UpdateUserRequestDataAttributes {
    pub fn new(membership: Option<crate::models::UpdateUserRequestDataAttributesMembership>) -> UpdateUserRequestDataAttributes {
        UpdateUserRequestDataAttributes {
            membership: if let Some(x) = membership {Some(Box::new(x))} else {None},
        }
    }
}


