/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateContainerImageRequestDataAttributes {
    #[serde(rename = "names")]
    pub names: Vec<String>,
}

impl UpdateContainerImageRequestDataAttributes {
    pub fn new(names: Vec<String>) -> UpdateContainerImageRequestDataAttributes {
        UpdateContainerImageRequestDataAttributes {
            names,
        }
    }
}


