/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateContainerImageRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::UpdateContainerImageRequestDataAttributes>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
}

impl UpdateContainerImageRequestData {
    pub fn new(attributes: crate::models::UpdateContainerImageRequestDataAttributes) -> UpdateContainerImageRequestData {
        UpdateContainerImageRequestData {
            attributes: Box::new(attributes),
            id: None,
            r#type: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "container_image")]
    ContainerImage,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ContainerImage
    }
}

