/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateEnvironmentRequestData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::EnvironmentUpdateAttributes>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl UpdateEnvironmentRequestData {
    pub fn new(r#type: String) -> UpdateEnvironmentRequestData {
        UpdateEnvironmentRequestData {
            attributes: None,
            r#type,
        }
    }
}


