/*
 * Snyk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: REST
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserAttributesMembership {
    /// The date the membership was established.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Whether the membership is a direct, or indirect membership.
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<Strategy>,
}

impl UserAttributesMembership {
    pub fn new() -> UserAttributesMembership {
        UserAttributesMembership {
            created_at: None,
            strategy: None,
        }
    }
}

/// Whether the membership is a direct, or indirect membership.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
    #[serde(rename = "direct")]
    Direct,
    #[serde(rename = "indirect")]
    Indirect,
}

impl Default for Strategy {
    fn default() -> Strategy {
        Self::Direct
    }
}

